import Head from 'next/head'
import Header from '../components/Header';
import Main from '../components/Main';
import TransactionHistory from '../components/TransactionHistory';

const style = {
  wrapper: `h-screen no-scrollbar max-h-screen h-min-screen w-screen bg-[#20242F] text-white select-none flex flex-col justify-between`,
};

export default function Home() {
  return (
    <div className={style.wrapper}>
      <Head>
        <title>Uniswap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Main />

      <TransactionHistory />

    </div>
  );
}
